[package]
name = "game"
version = "0.1.0"
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]

[dependencies]
engine = { path = "../engine" }
math = { path = "../math" }
wad = { path = "../wad" }

error-chain = "0.11.0"
glium = "0.17.0"
log = "0.3.6"
num = "0.1.32"
time = "0.1.35"

[dependencies.sdl2]
features = ["ttf"]
version = "0.30.0"
