[package]
name = "wad"
version = "0.1.0"
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]

[dependencies]
math = { path = "../math" }

bincode = "0.8.0"
byteorder = "1.1.0"
error-chain = "0.11.0"
log = "0.3.6"
num = "0.1.32"
ordermap = "0.2.11"
regex = "0.2.2"
serde = "1.0"
serde_derive = "1.0"
time = "0.1.35"
toml = "0.4.5"
vec_map = "0.8.0"
