# TOML metadata files describe things which were either hardcoded into
# the original games (such as what sky to display in which level), or things
# that were not applicable (how to display the sky when looking up or down).


### Sky metadata ###
#   The mapping between levels and sky textures was hardcoded in the original
# game. We decide which sky texture to use based on a regex applied to the name
# of the level.
#   The "tiled_band_size" field is required to deal with the fact that in the
# original game you couldn't look up or down so the sky textures were missing
# top and bottom bits. We fake these bits by mirroring and tiling as follows:
#
#                    Down -------------------------> Up
# Original texture:       |||||||||||ABCDEFG||||||||
# Faked bigger texture:   FGFEFGFEDCBABCDEFGFEFGFEFG
#                              |----|    |-|
#                                 |       |
#                                 |       --> Tiled band.
#                                 --> Full mirror.
#
# If this doesn't make it clear, read the code for `sky.frag' which actually
# does the rendering.

# DOOM 1 levels.
#   The tiled band size is as much sky as possible without grabbing the top of
# the mountains. Episode 2 is really frustrating because it has a very high
# peak, leaving a tiny amount of sky to tile.
[[sky]]
    level_pattern = "E1M."
    texture_name = "SKY1"
    tiled_band_size = 0.186

[[sky]]
    level_pattern = "E2M."
    texture_name = "SKY2"
    tiled_band_size = 0.086

[[sky]]
    level_pattern = "E3M."
    texture_name = "SKY3"
    tiled_band_size = 0.162

[[sky]]
    level_pattern = "E4M."
    texture_name = "SKY4"
    tiled_band_size = 1.0

# DOOM 2 levels.
#   Same goes for these levels, sky at the top being repeated. The first sky,
# however is _all_ sky, so the tiled band the whole sky (ABC -> CBABCBABCBABC).
[[sky]]
    level_pattern = "MAP(0[1-9]|10|11)"
    texture_name = "SKY1"
    tiled_band_size = 1.0

[[sky]]
    level_pattern = "MAP(1[2-9]|20)"
    texture_name = "SKY2"
    tiled_band_size = 0.25

[[sky]]
    level_pattern = "MAP(2[1-9]|32)"
    texture_name = "SKY3"
    tiled_band_size = 0.45


### Wall and Flat Animations ###
#   For both flats and walls, animations in the original DOOM were hardcoded:
# the game would look for the first and last frame in each animation and use all
# the textures/flats in between as animation frames.
#   We define these list of lists (a list of animations each containing a list
# of the frames which make it up.
[animations]
    flats = [
        ["NUKAGE1", "NUKAGE2", "NUKAGE3"],
        ["FWATER1", "FWATER2", "FWATER3", "FWATER4"],
        ["SWATER1", "SWATER2", "SWATER3", "SWATER4"],
        ["LAVA1", "LAVA2", "LAVA3", "LAVA4"],
        ["BLOOD1", "BLOOD2", "BLOOD3"],
        ["RROCK05", "RROCK06", "RROCK07", "RROCK08"],
        ["SLIME01", "SLIME02", "SLIME03", "SLIME04"],
        ["SLIME05", "SLIME06", "SLIME07", "SLIME08"],
        ["SLIME09", "SLIME10", "SLIME11", "SLIME12"],
    ]
    walls = [
        ["BLODGR1", "BLODGR2", "BLODGR3", "BLODGR4"],
        ["BLODRIP1", "BLODRIP2", "BLODRIP3", "BLODRIP4"],
        ["FIREBLU1", "FIREBLU2"],
        ["FIRELAV3", "FIRELAVA"],
        ["FIREMAG1", "FIREMAG2", "FIREMAG3"],
        ["FIREWALA", "FIREWALB", "FIREWALL"],
        ["GSTFONT1", "GSTFONT2", "GSTFONT3"],
        ["ROCKRED1", "ROCKRED2", "ROCKRED3"],
        ["SLADRIP1", "SLADRIP2", "SLADRIP3"],
        ["BFALL1", "BFALL2", "BFALL3", "BFALL4"],
        ["SFALL1", "SFALL2", "SFALL3", "SFALL4"],
        ["WFALL1", "WFALL2", "WFALL3", "WFALL4"],
        ["DBRAIN1", "DBRAIN2", "DBRAIN3",  "DBRAIN4"],
    ]


### Thing Directory ###
#   Thing types to sprites and behaviour were again hardcoded in the original
# game. We provide these by category (decoration etc.) each with their own
# properties.
[things]
    ### Decorations ###
    #   These don't do anything, they're just for show. Some are impassable
    # (obstacle = true) some not. Some are clipped to the ceiling (hanging =
    # true) some to the floor.

    # Bloody mess (an exploded player)
    [[things.decoration]]
        thing_type = 10
        sprite = "PLAY"
        sequence = "W"
        obstacle = false
        hanging = false

    # Same bloody mess.
    [[things.decoration]]
        thing_type = 12
        sprite = "PLAY"
        sequence = "W"
        obstacle = false
        hanging = false

    # Pool of blood and flesh
    [[things.decoration]]
        thing_type = 24
        sprite = "POL5"
        sequence = "A"
        obstacle = false
        hanging = false

    # Pool of blood
    [[things.decoration]]
        thing_type = 79
        sprite = "POB1"
        sequence = "A"
        obstacle = false
        hanging = false

    # Pool of blood
    [[things.decoration]]
        thing_type = 80
        sprite = "POB2"
        sequence = "A"
        obstacle = false
        hanging = false

    # Pool of brains
    [[things.decoration]]
        thing_type = 81
        sprite = "BRS1"
        sequence = "A"
        obstacle = false
        hanging = false

    # Dead player
    [[things.decoration]]
        thing_type = 15
        sprite = "PLAY"
        sequence = "N"
        obstacle = false
        hanging = false

    # Dead former human
    [[things.decoration]]
        thing_type = 18
        sprite = "POSS"
        sequence = "L"
        obstacle = false
        hanging = false

    # Dead former sergeant
    [[things.decoration]]
        thing_type = 19
        sprite = "SPOS"
        sequence = "L"
        obstacle = false
        hanging = false

    # Dead imp
    [[things.decoration]]
        thing_type = 20
        sprite = "TROO"
        sequence = "M"
        obstacle = false
        hanging = false

    # Dead demon
    [[things.decoration]]
        thing_type = 21
        sprite = "SARG"
        sequence = "N"
        obstacle = false
        hanging = false

    # Dead cacodemon
    [[things.decoration]]
        thing_type = 22
        sprite = "HEAD"
        sequence = "L"
        obstacle = false
        hanging = false

    # Dead lost soul, invisible
    [[things.decoration]]
        thing_type = 23
        sprite = "SKUL"
        sequence = "K"
        obstacle = false
        hanging = false

    # Tall, techno pillar
    [[things.decoration]]
        thing_type = 48
        sprite = "ELEC"
        sequence = "A"
        obstacle = true
        hanging = false

    # Tall green pillar
    [[things.decoration]]
        thing_type = 30
        sprite = "COL1"
        sequence = "A"
        obstacle = true
        hanging = false

    # Tall red pillar
    [[things.decoration]]
        thing_type = 32
        sprite = "COL3"
        sequence = "A"
        obstacle = true
        hanging = false

    # Short green pillar
    [[things.decoration]]
        thing_type = 31
        sprite = "COL2"
        sequence = "A"
        obstacle = true
        hanging = false

    # Short green pillar with beating heart
    [[things.decoration]]
        thing_type = 36
        sprite = "COL5"
        sequence = "AB"
        obstacle = true
        hanging = false

    # Short red pillar
    [[things.decoration]]
        thing_type = 33
        sprite = "COL4"
        sequence = "A"
        obstacle = true
        hanging = false

    # Short red pillar with skull
    [[things.decoration]]
        thing_type = 37
        sprite = "COL6"
        sequence = "A"
        obstacle = true
        hanging = false

    # Stalagmite.
    [[things.decoration]]
        thing_type = 47
        sprite = "SMIT"
        sequence = "A"
        obstacle = true
        hanging = false

    # Burnt tree: gray tree
    [[things.decoration]]
        thing_type = 43
        sprite = "TRE1"
        sequence = "A"
        obstacle = true
        hanging = false

    # Large brown tree
    [[things.decoration]]
        thing_type = 54
        sprite = "TRE2"
        sequence = "A"
        obstacle = true
        hanging = false

    # Floor lamp
    [[things.decoration]]
        thing_type = 2028
        sprite = "COLU"
        sequence = "A"
        obstacle = true
        hanging = false

    # Tall techno floor lamp
    [[things.decoration]]
        thing_type = 85
        sprite = "TLMP"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Short techno floor lamp
    [[things.decoration]]
        thing_type = 86
        sprite = "TLP2"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Candle
    [[things.decoration]]
        thing_type = 34
        sprite = "CAND"
        sequence = "A"
        obstacle = true
        hanging = false

    # Candelabra
    [[things.decoration]]
        thing_type = 35
        sprite = "CBRA"
        sequence = "A"
        obstacle = true
        hanging = false

    # Tall blue firestick
    [[things.decoration]]
        thing_type = 44
        sprite = "TBLU"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Tall green firestick
    [[things.decoration]]
        thing_type = 45
        sprite = "TGRE"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Tall red firestick
    [[things.decoration]]
        thing_type = 46
        sprite = "TRED"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Short blue firestick
    [[things.decoration]]
        thing_type = 55
        sprite = "SMBT"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Short green firestick
    [[things.decoration]]
        thing_type = 56
        sprite = "SMGT"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Short red firestick
    [[things.decoration]]
        thing_type = 57
        sprite = "SMRT"
        sequence = "ABCD"
        obstacle = true
        hanging = false

    # Burning barrel
    [[things.decoration]]
        thing_type = 70
        sprite = "FCAN"
        sequence = "ABC"
        obstacle = true
        hanging = false

    # Evil Eye: floating eye in symbol, over candle
    [[things.decoration]]
        thing_type = 41
        sprite = "CEYE"
        sequence = "ABCB"
        obstacle = true
        hanging = false

    # Floating Skull: flaming skull-rock
    [[things.decoration]]
        thing_type = 42
        sprite = "FSKU"
        sequence = "ABC"
        obstacle = true
        hanging = false

    # Hanging victim, twitching
    [[things.decoration]]
        thing_type = 49
        sprite = "GOR1"
        sequence = "ABCB"
        obstacle = true
        hanging = true

    # Hanging victim, twitching
    [[things.decoration]]
        thing_type = 63
        sprite = "GOR1"
        sequence = "ABCB"
        obstacle = true
        hanging = true

    # Hanging victim, arms out
    [[things.decoration]]
        thing_type = 50
        sprite = "GOR2"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging victim, arms out
    [[things.decoration]]
        thing_type = 59
        sprite = "GOR2"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging pair of legs
    [[things.decoration]]
        thing_type = 52
        sprite = "GOR4"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging pair of legs
    [[things.decoration]]
        thing_type = 60
        sprite = "GOR4"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging victim, 1-legged
    [[things.decoration]]
        thing_type = 51
        sprite = "GOR3"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging victim, 1-legged
    [[things.decoration]]
        thing_type = 61
        sprite = "GOR3"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging leg
    [[things.decoration]]
        thing_type = 53
        sprite = "GOR5"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging leg
    [[things.decoration]]
        thing_type = 62
        sprite = "GOR5"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging victim, guts removed
    [[things.decoration]]
        thing_type = 73
        sprite = "HDB1"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging victim, guts and brain removed
    [[things.decoration]]
        thing_type = 74
        sprite = "HDB2"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging torso, looking down
    [[things.decoration]]
        thing_type = 75
        sprite = "HDB3"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging torso, open skull
    [[things.decoration]]
        thing_type = 76
        sprite = "HDB4"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging torso, looking up
    [[things.decoration]]
        thing_type = 77
        sprite = "HDB5"
        sequence = "A"
        obstacle = true
        hanging = true

    # Hanging torso, brain removed
    [[things.decoration]]
        thing_type = 78
        sprite = "HDB6"
        sequence = "A"
        obstacle = true
        hanging = true

    # Impaled human
    [[things.decoration]]
        thing_type = 25
        sprite = "POL1"
        sequence = "A"
        obstacle = true
        hanging = false

    # Twitching impaled human
    [[things.decoration]]
        thing_type = 26
        sprite = "POL6"
        sequence = "AB"
        obstacle = true
        hanging = false

    # Skull on a pole
    [[things.decoration]]
        thing_type = 27
        sprite = "POL4"
        sequence = "A"
        obstacle = true
        hanging = false

    # 5 skulls shish kebob
    [[things.decoration]]
        thing_type = 28
        sprite = "POL2"
        sequence = "A"
        obstacle = true
        hanging = false

    # Pile of skulls and candles
    [[things.decoration]]
        thing_type = 29
        sprite = "POL3"
        sequence = "AB"
        obstacle = true
        hanging = false
