[package]
name = "gl"
version = "0.0.1"
authors = ["Cristian Cobzarenco <cristi.cobzarenco@gmail.com>"]

[lib]
name = "gl"
path = "lib.rs"

[dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

