[package]
name = "gfx"
version = "0.0.1"
authors = ["Cristian Cobzarenco <cristi.cobzarenco@gmail.com>"]

[lib]
name = "gfx"
path = "lib.rs"

[dependencies.gl]
path = "../gl"

[dependencies.math]
path = "../math"

[dependencies.base]
path = "../base"

[dependencies]
log = "*"
